# Generated by Django 3.2.8 on 2021-11-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assignment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
