# Generated by Django 3.2.8 on 2021-11-26 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_assignment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='ta',
            field=models.ManyToManyField(blank=True, related_name='ta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courses',
            name='users_enrolled',
            field=models.ManyToManyField(blank=True, related_name='users_enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
