# Generated by Django 3.2.8 on 2021-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211126_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='codestudent',
            field=models.CharField(default='abcde', max_length=5),
        ),
        migrations.AddField(
            model_name='courses',
            name='codeta',
            field=models.CharField(default='abcde', max_length=5),
        ),
    ]
