# Generated by Django 3.2.8 on 2021-11-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211127_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='weightage',
            field=models.IntegerField(default=0),
        ),
    ]
