# Generated by Django 3.2.8 on 2021-11-28 06:03

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_submission_marksgot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='ansfile',
            field=models.FileField(upload_to=myapp.models.Submission.upload_file_name),
        ),
    ]
