# Generated by Django 3.2.8 on 2021-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_submission_ansfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marksgot',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
