from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('',views.home, name='home'),
    path('register/',views.register,name='register'),
    path('profile/',views.profile,name='profile'),
    path('createdcourses/', views.createdcourses, name='createdcourses'),
    path('courseslist/', views.courseslist,name = 'courseslist'),
    path('enrolledcourses/',views.enrolledcourses,name = "enrolledcourses"),
    path('inviteta/<int:course_id>/<int:user_id>',views.inviteta,name = "inviteta"),
    path('invitestudent/<int:course_id>/<int:user_id>',views.invitestudent,name = "invitestudent"),
    path('tacourses/',views.tacourses,name = "tacourses"),
    path('courseinfo/<int:course_id>',views.courseinfo,name="courseinfo"),
    path('courseinfocreated/<int:course_id>',views.courseinfocreated,name="courseinfocreated"),
    path('login/',auth_view.LoginView.as_view(template_name='myapp/login.html'),name="login"),
    path('sendaddrequest/<int:course_id>',views.sendaddrequest,name = 'sendaddrequest'),
    path('joincoursestudent/<int:course_id>',views.joincoursestudent,name = 'joincoursestudent'),
    path('joincourseta/<int:course_id>',views.joincourseta,name = 'joincourseta'),
    path('acceptaddrequest/<int:request_id>', views.acceptaddrequest, name = 'acceptaddrequest'),
    path('logout/',auth_view.LogoutView.as_view(template_name='myapp/logout.html'),name="logout"),
    path('addassignment/<int:course_id>',views.upload_assignment,name='addassignment'),
    path('explore/<int:course_id>',views.explore,name='explore'),
    path('createnewcourse/',views.createnewcourse,name = "createnewcourse"),
    path('viewAssignment/<int:assignment_id>',views.viewAssignment,name='viewAssignment'),
    path('editprofile/',views.editprofile,name='editprofile'),
    path('addsubmission/<int:assignment_id>',views.addsubmission,name = 'addsubmission'),
    path('addcomment/<int:dis_id>',views.addcomment,name='addcomment'),
    path('directmessage/', views.direct_message,name = 'directmessage'),
    path('uploadcsv/<int:assignment_id>',views.uploadcsv,name = 'uploadcsv'),
    path('reset_password/',auth_view.PasswordResetView.as_view(template_name="myapp/password_reset.html"),name='reset_password'),
    path('reset_password_sent/', auth_view.PasswordResetDoneView.as_view(template_name="myapp/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(template_name="myapp/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_view.PasswordResetCompleteView.as_view(template_name="myapp/password_reset_done.html"), name="password_reset_complete"),
    path('todo/<int:course_id>',views.todo, name="todo"),
    path('discthread/<int:dis_id>',views.discthread, name = "discthread"),
    path('adddiscthread/<int:course_id>',views.adddiscthread, name = "adddiscthread"),
]
